export const GET_PAYMENTS_CONST = "GET_PAYMENTS";
export const SET_PAYMENT_DATA_CONST = "SET_PAYMENT_DATA";
export const SET_PAYMENT_NAME_CONST = "SET_PAYMENT_NAME";
export const SET_PAYMENT_NOTE_CONST = "SET_PAYMENT_NOTE";
export const SET_PAYMENT_SUM_CONST = "SET_PAYMENT_SUM";
export const SET_PAYMENT_ACCOUNT_NUMBER_CONST = "SET_PAYMENT_ACCOUNT_NUMBER";
export const SET_VALIDATION_RESULT_CONST = "SET_VALIDATION_RESULT";
export const RESET_DATA_PAYMENT_CONST = "RESET_DATA_PAYMENT";
