export const SET_PAYMENT_SUM_NUMBER_CONST = 1;
export const SET_PAYMENT_NAME_NUMBER_CONST = 2;
export const SET_PAYMENT_NOTE_NUMBER_CONST = 3;
export const SET_PAYMENT_ACCOUNT_NUMBER_NUMBER_CONST = 4;