export const ADD_PAYMENT_INFO_CONST = "ADD_PAYMENT_INFO";
export const SET_IS_READY_CONST = "SET_IS_READY";
export const RESET_DATA_CONST = "RESET_DATA";
export const SET_ONLY_INPUT_CONST = "SET_ONLY_INPUT";
export const SET_ONLY_OUTPUT_CONST = "SET_ONLY_OUTPUT";
export const CHANGE_SELECTED_VALUE_CONST = "CHANGE_SELECTED_VALUE";
export const SET_FIND_VALUE_CONST = "SET_FIND_VALUE";