export const ADD_PHOTO_CONSTANT = "ADD_PHOTO";
export const CHANGE_RATING_CONSTANT = "CHANGE_RATING";
export const MAKE_ONE_PHOTO_FOR_TEST_CONSTANT = "MAKE_ONE_PHOTO_FOR_TEST";
export const SORT_PHOTOS_CONSTANT = "SORT_CONSTANT";
export const ORDER_BY_CONSTANT = "ORDER_BY";
export const ORDER_BY_DESC_CONSTANT = "ORDER_BY_DESC";
export const COUNT_PHOTOS_IN_MAIN_CONSTANT = 21;