export const REGISTRATION_USER_CONSTANT = "REGISTRATION_USER";
export const SET_FIRST_NAME_CONSTANT = "SET_FIRST_NAME";
export const SET_SECOND_NAME_CONSTANT = "SET_SECOND_NAME";
export const SET_EMAIL_FOR_REG_CONSTANT = "SET_EMAIL_FOR_REG";
export const SET_PASSWORD_FIRST_CONSTANT = "SET_PASSWORD_FIRST";
export const SET_PASSWORD_SECOND_CONSTANT = "SET_PASSWORD_SECOND";