export const SET_FIRST_NAME_NUMBER_CONSTANT = 3;
export const SET_SECOND_NAME_NUMBER_CONSTANT = 4;
export const SET_EMAIL_FOR_REG_NUMBER_CONSTANT = 5;
export const SET_PASSWORD_FIRST_NUMBER_CONSTANT = 6;
export const SET_PASSWORD_SECOND_NUMBER_CONSTANT = 7;