export const SET_APIKEY_CONSTANT = "SET_APIKEY";
export const SET_EMAIL_CONSTANT = "SET_EMAIL";
export const SET_PASSWORD_CONSTANT = "SET_PASSWORD";
export const SET_RESULTS_VALIDATION_AUTH_CONST = "SET_RESULTS_VALIDATION_AUTH";
export const RESET_DATA_CONST = "RESET_DATA";